# Generated by Django 4.0.6 on 2022-11-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0010_chatroom_last_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='has_unread',
            field=models.BooleanField(default=False),
        ),
    ]
